import Head from 'next/head';
import { Provider } from "react-redux";
import { ThemeProvider } from 'styled-components';
import theme from 'theme/main.json';
import { store } from "../store";
import GlobalStyles from "./globalStyles";

const MyApp = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <ThemeProvider theme={theme}>
          <GlobalStyles />
          <Component {...pageProps} />
        </ThemeProvider>
      </Provider>
    </>
  );
};

export default MyApp;
